export const LogActions = {
    ACCOUNT_CREATION: "ACCOUNT_CREATION",
    UPDATE_PFP: "UPDATE_PFP",
    ADD_BALANCE: "ADD_BALANCE",
    WITHDRAW_BALANCE: "WITHDRAW_BALANCE",
    TRANSFER_BALANCE: "TRANSFER_BALANCE",
    ADD_ACCOUNT: "ADD_ACCOUNT",
    REMOVE_ACCOUNT: "REMOVE_ACCOUNT",
    ADD_BILL: "ADD_BILL",
    PAY_BILL: "PAY_BILL",
    ADD_GOAL: "ADD_GOAL",
    UPDATE_GOAL: "UPDATE_GOAL",
};
